class Action:
    MANAGE_MEMBERSHIP = "MANAGE_MEMBERSHIP"
    MANAGE_ATTENDANCE = "MANAGE_ATTENDANCE"
    VIEW_ACTIVE_MEMBERSHIP = "VIEW_ACTIVE_MEMBERSHIP"
    VIEW_ALL_MEMBERSHIPS = "VIEW_ALL_MEMBERSHIPS"
    CHECK_IN = "CHECK_IN"
    VIEW_ATTENDANCES = "VIEW_ATTENDANCES"
    CHANGE_SETTINGS = "CHANGE_SETTINGS"
    CHANGE_NAME = "CHANGE_NAME"
    CHANGE_PHONE = "CHANGE_PHONE"
    CHANGE_LOCALE = "CHANGE_LOCALE"
    ADD_MEMBERSHIP = "ADD_MEMBERSHIP"
    FREEZE_MEMBERSHIP = "FREEZE_MEMBERSHIP"
    UNFREEZE_MEMBERSHIP = "UNFREEZE_MEMBERSHIP"
    REGISTER = "REGISTER"
    DELETE_USER = "DELETE_USER"
    CANCEL = "CANCEL"


class Modifier:
    BUTTON = "_button"
    TEXT = "_text"
    CALLBACK = "_callback"
    MEMBER = "member_"
    ADMIN = "admin_"


class MenuButtons:
    ACTIVE_MB = [Action.VIEW_ACTIVE_MEMBERSHIP, Action.CHECK_IN]
    CHECK_INS = [Action.VIEW_ATTENDANCES]
    REGISTERED = [
        Action.CHANGE_NAME,
        Action.CHANGE_PHONE,
        Action.CHANGE_LOCALE,
        Action.DELETE_USER,
    ]
    MANAGE_MB = [
        f"{Modifier.ADMIN}{Action.ADD_MEMBERSHIP}",
        f"{Modifier.ADMIN}{Action.FREEZE_MEMBERSHIP}",
    ]
    ADMIN = [f"{Action.MANAGE_MEMBERSHIP}", Action.MANAGE_ATTENDANCE]


class Environment:
    PROD = "PROD"
    TEST = "TEST"
