name: membership_bot

on:
  push:
    branches-ignore:
      - '!master'

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt
          sudo apt-get install gettext
      - name: Lint with ruff
        run: |
          ruff check
      - name: Compile translations
        run: |
          msgfmt -o ./src/locales/ru/LC_MESSAGES/mb_bot.mo ./src/locales/ru/LC_MESSAGES/mb_bot.po
          msgfmt -o ./src/locales/en/LC_MESSAGES/mb_bot.mo ./src/locales/en/LC_MESSAGES/mb_bot.po
      - name: Run Test
        if: always()
        run: pytest --alluredir=allure-results
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history